hw03: student_test.c File Reference
student_test.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "student.h"
Typedefs
typedef struct Student Student
Functions
int main (int argc, char *argv[])
Typedef Documentation
Student
typedef struct Student Student
struct_test.c
Author
Ryan Mechery Tests functionality of custom Student struct
Function Documentation
main()
int main (int argc, char * argv[])
References free_students(), make_deep_copy(), make_random_structs(), make_shallow_copy(), make_student(), print_student(), and print_students().