hw03: student.c File Reference
student.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "mystring.h"
#include "student.h"
#include <time.h>
Data Structures
struct Student
This structure represents a student object in school.
Macros
#define MAX_NAME_SIZE (30)
Typedefs
typedef struct Student Student
Functions
Student * make_student (char *name, int age, int id, double gpa)
void print_student (Student *st)
Student * make_random_student ()
Student ** make_students (int num_students)
void print_students (Student **st, int num)
int main ()
Macro Definition Documentation
MAX_NAME_SIZE
#define MAX_NAME_SIZE (30)
student.c
Author
Ryan Mechery Defines custom struct for a Student with a name, age, id, and grades[].
Typedef Documentation
Student
typedef struct Student Student
Function Documentation
main()
int main ()
References make_students(), and print_students().
make_random_student()
Student* make_random_student ()
Use make_student() with random values to make random student struct
Returns
pointer to random Student struct
References Student::age, generate_random_name(), Student::gpa, make_student(), MAX_NAME_SIZE, and Student::name.
Referenced by make_students().
make_student()
Student* make_student (char * name, int age, int id, double gpa)
Dynamically allocates and returns pointer to a student struct in the heap.
Parameters
name c-string pointer for Student.name
age int for Student.age
id int for Student.id
gpa double for Student.gpa
Warning
If there is no space in memory, this method will return a null pointer.
References Student::age, Student::gpa, Student::id, MAX_NAME_SIZE, mystrncpy(), and Student::name.
Referenced by make_random_student().
make_students()
Student** make_students (int num_students)
This function returns an array of pointers to random student structs.
Parameters
num_students number of students to be stored in array
Returns
array of student pointers
Warning
this function will return null if there isn't enough space in memory for specified student collection
References make_random_student().
Referenced by main().
print_student()
void print_student (Student * st)
Prints student struct with formatting
Parameters
st pointer to Student struct
References Student::age, Student::gpa, Student::id, and Student::name.
Referenced by print_students().
print_students()
void print_students (Student ** st, int num)
This function prints out num Student structs with formatting.
Parameters
st array of Student pointers
number of st structs to print out
Warning
If you pass in a null pointer, this function will catch it but it will NOT stop the program.
References print_student().
Referenced by main().