hw03: student.h File Reference
student.h File Reference
Typedefs
typedef struct Student Student
Functions
Student * make_student (char *name, int age, int id, double gpa)
void print_student (Student *st)
void print_students (Student **st, int num)
Student ** make_shallow_copy (Student **og_st, int size)
Student ** make_deep_copy (Student **og_st, int size)
Student ** make_random_structs (int num_students)
void free_students (Student **st, int size)
Typedef Documentation
Student
typedef struct Student Student
student.h
Author
Ryan Mechery, Mike Ciaraldi, Blake Nelson Header file for functions in student.c file Note: not all functions are included here. Only ones relevant to the tester are included.
Function Documentation
free_students()
void free_students (Student ** st, int size)
Free all Structs in an array from the heap and set pointer to NULL
Parameters
st array of Student structs @size size number of structs in st
Warning
By setting pointers to null after struct has been deallocated, it deletes memory addresses in original student struct. However if a shallow_copy was created, it won't delete those pointers from memory. User must keep this in mind.
Referenced by main().
make_deep_copy()
Student** make_deep_copy (Student ** og_st, int size)
Return the deepest possible copy of Student struct collection by allocating memory for copies of Student structs and copying in struct members.
Parameters
og_st array of Student structs @size size number of structs in st
Returns
pointer to deepest copy of og_st
Warning
This method should be null safe for structs only. May result in an error if pointers in struct members are null.
References make_student().
Referenced by main().
make_random_structs()
Student** make_random_structs (int num_students)
This function returns an array of pointers to random student structs.
Parameters
num_students number of students to be stored in array
Returns
array of student pointers
Warning
this function will return null if there isn't enough space in memory for specified student collection
References make_random_student().
Referenced by main().
make_shallow_copy()
Student** make_shallow_copy (Student ** og_st, int size)
Given an array of Student structs, return a shallow copy with an array of pointers
Parameters
og_st array of Student structs
size number of structs in og_st
Returns
array of Student struct pointers
Warning
If there isn't enough space in memory, this function returns a NULL pointer.
Referenced by main().
make_student()
Student* make_student (char * name, int age, int id, double gpa)
Dynamically allocates and returns pointer to a student struct in the heap.
Parameters
name c-string pointer for Student.name
age int for Student.age
id int for Student.id
gpa double for Student.gpa
Returns
pointer to new Student struct
Warning
If there is no space in memory, this method will return a null pointer. Also, it is the user's responsibility to make sure name is null-terminated.
References Student::age, Student::gpa, Student::id, MAX_NAME_SIZE, mystrncpy(), and Student::name.
Referenced by main(), make_deep_copy(), and make_random_student().
print_student()
void print_student (Student * st)
Prints fields of student struct with formatting
Parameters
st pointer to Student struct
Warning
Student pointer cannot be null!
References Student::age, Student::gpa, HORZ_BAR, Student::id, and Student::name.
Referenced by main(), and print_students().
print_students()
void print_students (Student ** st, int num)
This function prints out num Student structs with formatting.
Parameters
st array of Student pointers
number of st structs to print out
Warning
If you pass in a null pointer, this function will catch it but it will NOT stop the program.
References HORZ_BAR, and print_student().
Referenced by main().