hw02: array_sort.h File Reference
array_sort.h File Reference
Functions
void sort_int_array (int arr[], int size)
void sort_double_array (double arr[], int size)
int get_random (int max)
void fill_random (int arr[], int size, int max)
Function Documentation
fill_random()
void fill_random (int arr[], int size, int max)
function that uses get_random() to populate arr with random integers
Parameters
arr array to be populated
size size of arr array
max max number in range inclusive
References get_random().
Referenced by main().
get_random()
int get_random (int max)
function returns a (pseudo) random integer from zero to max, inclusive
Parameters
max max number in range inclusive
Returns
random integer from [0, max]
Warning
Initialize seed generator BEFORE using this function
Referenced by fill_random().
sort_double_array()
void sort_double_array (double arr[], int size)
Sort double arr in place using bubbleSort.
Parameters
arr array to be sorted
size size of arr array
Referenced by main().
sort_int_array()
void sort_int_array (int arr[], int size)
File array_sort.h
Author
Ryan Mechery
Header file for functions that sort arrays.
File array_sort.c
Author
Ryan Mechery
Functions for sorting arrays and generating random numbers. Sort int arr in place using bubbleSort.
Parameters
arr array to be sorted
size size of arr array
Referenced by main().