hw02: at2.c File Reference
at2.c File Reference
#include <stdio.h>
#include "print_arrays.h"
#include "array_sort.h"
Macros
#define DOUBLE_ARRAY_SIZE (10)
Functions
int main (int argc, const char *argv[])
Macro Definition Documentation
DOUBLE_ARRAY_SIZE
#define DOUBLE_ARRAY_SIZE (10)
file at2.c
Author
Ryan Mechery
Program to demonstrate populating fixed-size arrays in C using input from command line and sorting them.
Function Documentation
main()
int main (int argc, const char * argv[])
Main program for demonstrating arrays. Fills array contents from cmd line, prints it out, and sorts it.
Returns
0, Indicating success.
1, Indicating Error.
References DOUBLE_ARRAY_SIZE, get_double_input(), print_double_array(), and sort_double_array().