Lab06: fed2cs2303.c File Reference
fed2cs2303.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include <forward_list>
#include "zipfed.hpp"
Macros
#define SZ_FILENAME (129)
Functions
ssize_t readln_fed (char **lineptr, size_t *n, FILE *stream)
int main (int argc, char *argv[])
Macro Definition Documentation
SZ_FILENAME
#define SZ_FILENAME (129)
Program to read in public zip code information and store as needed for cs2301 assignment needs.
Author
Blake Nelson
Function Documentation
main()
int main (int argc, char * argv[])
main function to drive program. Input and output file names specified on command line.
usage: fed2cs2301 input_file output_file
The input file must already exist. Output file will be created.
Approach: 1) Open both input and output files, or fail with error 2) Read a line from input. This is a record of federal zip code data Note: the first line of the file is header info, not data, ignore it 3) Parse the input line to populate a ZIP_FEDERAL structure 4) Write the ZIP_FEDERAL structure to output file 1 record / line Note: no column header information will be written out, just data fields 5) Close output and input files and exit cleanly
Parameters
argc is the number of input strings - will be 3
argv is array of cmd line args - fed2cs2301 existing_input_file output_file_to_create
Returns
0 for success. non-zero for error
References Zipfed::parse_zip_federal(), Zipfed::parse_zip_MA(), Zipfed::print(), readln_fed(), and SZ_FILENAME.
readln_fed()
ssize_t readln_fed (char ** lineptr, size_t * n, FILE * stream)
Function to read a line from the US FED and return pointer to the line of data represented as a C-String (i.e. NULL terminated string)
@lineptr is a pointer to the dynamically allocated buffer to fill. If the pointer is NULL, a buffer will be allocated to hold the line. If the buffer is too small to hold the line, realloc will be called to allocate a larger buffer. If the buffer is reallocated, n will be set to new size.
is a pointer to the size of the buffer pointer to be lineptr. If memory is reallocated for lineptr, the size of n will be incremented accordingly. The parameter n will always specify the size of buffer pointed at by lineptr. @fptr is the FILE pointer to the open file to read.
Returns
number bytes (chars) read or -1 on error
Referenced by main().