Lab05: stack.h File Reference
stack.h File Reference
Data Structures
struct stack
Macros
#define SZ_STACK (120)
Typedefs
typedef struct stack Stack
Functions
void * peek (Stack *stack)
void * pop (Stack *stack)
void * push (Stack *stack, void *element)
int isempty (Stack *stack)
int numelements (Stack *stack)
int maxelements (Stack *stack)
Stack * create (void)
void destroy (Stack *stack)
Macro Definition Documentation
SZ_STACK
#define SZ_STACK (120)
Header file for stack data structure implementation
Author
Blake Nelson
Typedef Documentation
Stack
typedef struct stack Stack
Function Documentation
create()
Stack* create (void)
Functions to support Stack implementation. Each stack element is a pointer to void. This allows any type of object to be stored on the stack
Author
Blake Nelson Function to create a stack with defined size. The returned Stack structure must be passed to each stack operation to identify the stack and its state.
Returns
pointer to Stack structure or NULL on error
References stack::base, and stack::top.
Referenced by main().
destroy()
void destroy (Stack * stack)
Function to destroy a stack and return memory resources to heap. Note: the memory for the stack struct used to track configuration of the stack is returned to heap, the memory (void pointer to) elements which might currently exist in the stack are not released back to the stack.
Note: It is the responsibility of the user of the stack to manage elements. Note2: It is the responsibility of the user of the stack to manage the pointer to the stack struct. (The stack struct is returned to the memory heap, but the calling code still has a pointer to the, now freed, stack struct. That pointer should be set to NULL upon return from this function.)
Parameters
stack is a pointer to the stack struct. Invalid upon function return.
Returns
none.
isempty()
int isempty (Stack * stack)
Function to return whether the stack is empty. If empty returns non-zero.
Parameters
stack is a pointet to the stack
Returns
non-zero (true) if empty or zero (false) if not empty
References numelements().
Referenced by main().
maxelements()
int maxelements (Stack * stack)
Function to return the max number of elements the stack can hold
Parameters
stack is a pointer to the stack
Returns
the maximum number of elements the stack can hold
References stack::elements.
Referenced by push().
numelements()
int numelements (Stack * stack)
Function to return the number of elements currently in the stack
Parameters
stack is a pointer to the stack
Returns
the number of elements currently in the stack
References stack::num_elements.
Referenced by isempty().
peek()
void* peek (Stack * stack)
Function prototypes for stack operations
Function to support peeking at the current top of stack. This function will return the top element of the stack without removing it from the stack. the state of the stack will not be changed by this function.
Parameters
stack is a pointer to the stack
Returns
the element on top of stack or null if the stack is empty
References stack::num_elements, and stack::top.
Referenced by main(), pop(), and push().
pop()
void* pop (Stack * stack)
Function to pop the top stack element and return to caller. This will remove the top element and modify the state of the stack.
top of stack pointer is modified (moved) top element of stack is removed from the stack top slot (where the element was) is set to NULL for ease of debugging number of elements in stack is decremented by one
Parameters
stack is a pointer to the stack
Returns
the top element from the stack or null if the stack is empty
References stack::num_elements, peek(), and stack::top.
Referenced by main().
push()
void* push (Stack * stack, void * element)
Function to push element onto stack. A pointer to the top element of the stack is returned upon success. If the stack is full, the element will not be pushed onto the stack and NULL will be returned.
new element is inserted into stack at current top (pointer to by top) top of stack pointer is modified (moved to next position) number of elements in stack is incremented by one
Parameters
stack is a pointer to the stack
element is a pointer to the element to pus onto stack (which is itself a pointer to void)
Returns
a pointer to the element pushed onto the stack or NULL on failure
References stack::base, stack::elements, maxelements(), stack::num_elements, peek(), and stack::top.
Referenced by main().