HW06: zipcode.c File Reference
zipcode.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <string>
#include <forward_list>
#include <readline/readline.h>
#include <readline/history.h>
#include <iostream>
#include "zipfed.hpp"
Macros
#define SZ_FILENAME (129)
#define MAXLINE (4096)
Functions
ssize_t readln_fedcs2303 (char **lineptr, size_t *n, FILE *stream)
bool comparator_function (Zipfed *pZip1, Zipfed *pZip2)
int main (int argc, char *argv[])
Macro Definition Documentation
MAXLINE
#define MAXLINE (4096)
SZ_FILENAME
#define SZ_FILENAME (129)
Program demonstrating parsing and linked lists. This program supports zip code lookup for any town in Massachusetts
Author
Blake Nelson, Ryan Mechery
Function Documentation
comparator_function()
bool comparator_function (Zipfed * pZip1, Zipfed * pZip2)
Custom comparator for forward list based on zipfed city attr.
Parameters
pZip1 pointer to first zipfed object
pZip2 pointer to second zipfed object
Returns
true if pZip1.city lex. less than pZip2.city
false
References Zipfed::get_city().
Referenced by main().
main()
int main (int argc, char * argv[])
program to find the zip code for any town in Massachusetts
Parameters
argc is the number of field on command line - should be 1
argv is array of strings entered on command line - prog name
Returns
0 for success
1 for failure
References comparator_function(), Zipfed::get_zip(), Zipfed::is_from(), MAXLINE, Zipfed::parse_zip_cs2303(), readln_fedcs2303(), and SZ_FILENAME.
readln_fedcs2303()
ssize_t readln_fedcs2303 (char ** lineptr, size_t * n, FILE * stream)
Function to read a line from the fed2cs2303 zip and return pointer to the line of data represented as a C-String (i.e. NULL terminated string)
@lineptr is a pointer to the dynamically allocated buffer to fill. If the pointer is NULL, a buffer will be allocated to hold the line. If the buffer is too small to hold the line, realloc will be called to allocate a larger buffer. If the buffer is reallocated, n will be set to new size.
is a pointer to the size of the buffer pointer to be lineptr. If memory is reallocated for lineptr, the size of n will be incremented accordingly. The parameter n will always specify the size of buffer pointed at by lineptr. @fptr is the FILE pointer to the open file to read.
Returns
number bytes (chars) read or -1 on error
Referenced by main().