HW04: sort.c File Reference
sort.c File Reference
#include <stdio.h>
#include <sys/time.h>
#include "sort.h"
Functions
void print_int_array (int nums[], int count)
void sort_descending (int nums[], int count)
void alt_sort_descending (int nums[], int count)
void print_timeval (struct timeval t)
struct timeval timediff (struct timeval time1, struct timeval time2)
int get_random (int max)
void fill_random (int arr[], int size, int max)
Function Documentation
alt_sort_descending()
void alt_sort_descending (int nums[], int count)
Sorts an array of integers into descending order. Uses the bubble sort algorithm w/pointers.
Parameters
nums Array to print
count Number of elements to print
Referenced by timesort().
fill_random()
void fill_random (int arr[], int size, int max)
function that uses get_random() to populate arr with random integers
Parameters
arr array to be populated
size size of arr array
max max number in range inclusive
References get_random().
Referenced by main().
get_random()
int get_random (int max)
function returns a (pseudo) random integer from zero to max, inclusive
Parameters
max max number in range inclusive
Returns
random integer from [0, max]
Warning
Initialize seed generator BEFORE using this function
Referenced by fill_random().
print_int_array()
void print_int_array (int nums[], int count)
sort.c
Author
Ryan Mechery This file lists implementation for sort funcs and related printing funcs defined in sort.h Prints an array of integers, one per line.
Parameters
nums Array to print
count Number of elements to print
Referenced by timesort().
print_timeval()
void print_timeval (struct timeval t)
Prints the contents of a timeval struct.
Parameters
t Struct to print.
Referenced by timesort().
sort_descending()
void sort_descending (int nums[], int count)
Sorts an array of integers into descending order. Uses the bubble sort algorithm.
Parameters
nums Array to print
count Number of elements to print
Referenced by timesort().
timediff()
struct timeval timediff (struct timeval time1, struct timeval time2)
Calculates difference between two timestamps. Note that this takes structs as parameters and returns a struct; it does not use pointers.
Parameters
time1 A time stamp
time2 another timestamp (assumed same as or later than time 1)
Returns
A timeval struct representing time2 - time1
Referenced by timesort().