HW04: timesort.c File Reference
timesort.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <sys/time.h>
#include "sort.h"
Functions
void timesort (int a[], int count, int sort_type)
Function Documentation
timesort()
void timesort (int a[], int count, int sort_type)
Program which takes an array of integers, prints it, sorts it, prints it again, and reports how long the sorting took.
Parameters
a Array of integers.
count Number of integers in the array.
Returns
0 if success, 1 if error (wrong number of arguments)
References alt_sort_descending(), print_int_array(), print_timeval(), sort_descending(), and timediff().
Referenced by main().